version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm cache clean --force
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Zipping application for Lambda..."
      - zip -r my-node-app.zip .
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp my-node-app.zip s3://my-node-app-bucket/
artifacts:
  files:
    - my-node-app.zip
